apiVersion: v2
name: hik-stream
description: Kéo stream đầu ghi Hikvision qua cổng SDK theo nhu cầu, phát HLS nội bộ bằng mediamtx
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/phuthuycoding/hik-connect-proxy-viewer
sources:
  - https://github.com/phuthuycoding/hik-connect-proxy-viewer
maintainers:
  - name: PhuthuyCoding
    email: tamanhquyen.it@gmail.com
keywords:
  - hikvision
  - mediamtx
  - hls
