apiVersion: v1
kind: Service
metadata:
  name: {{ include "hcpv.streamName" . }}
  labels:
    {{- include "hcpv.labels" . | nindent 4 }}
    app.kubernetes.io/component: stream
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: hls
      protocol: TCP
      name: hls
    - port: 9000
      targetPort: discovery
      protocol: TCP
      name: discovery
    - port: 9001
      targetPort: timelapse
      protocol: TCP
      name: timelapse
  selector:
    {{- include "hcpv.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: stream
