apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hik-stream.fullname" . }}-config
  labels:
    {{- include "hik-stream.labels" . | nindent 4 }}
data:
  mediamtx.yml: |
    {{- .Files.Get "files/mediamtx.yml" | nindent 4 }}
