apiVersion: v1
kind: Service
metadata:
  name: {{ include "hik-stream.fullname" . }}
  labels:
    {{- include "hik-stream.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.hlsPort }}
      targetPort: 8888
      protocol: TCP
      name: hls
    - port: {{ .Values.service.discoveryPort }}
      targetPort: 9000
      protocol: TCP
      name: discovery
  selector:
    {{- include "hik-stream.selectorLabels" . | nindent 4 }}
