apiVersion: v2
name: hik-web
description: Trang web xem cam lớp, màn login mật khẩu, proxy HLS về hik-stream
type: application
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/phuthuycoding/hik-connect-proxy-viewer
sources:
  - https://github.com/phuthuycoding/hik-connect-proxy-viewer
maintainers:
  - name: PhuthuyCoding
    email: tamanhquyen.it@gmail.com
keywords:
  - hikvision
  - hls
  - web
