"""
HCNetSDK Constants and Error Codes
"""

# Buffer size constants
NET_DVR_DEV_ADDRESS_MAX_LEN = 129
NET_DVR_LOGIN_USERNAME_MAX_LEN = 64
NET_DVR_LOGIN_PASSWD_MAX_LEN = 64
SERIALNO_LEN = 48
STREAM_ID_LEN = 32
NAME_LEN = 32
PASSWD_LEN = 16
MAX_NAMELEN = 16

# File search return codes
NET_DVR_FILE_SUCCESS = 1000
NET_DVR_FILE_NOFIND = 1001
NET_DVR_ISFINDING = 1002
NET_DVR_NOMOREFILE = 1003
NET_DVR_FILE_EXCEPTION = 1004

# Stream types
STREAM_TYPE_MAIN = 0
STREAM_TYPE_SUB = 1
STREAM_TYPE_THIRD = 2
STREAM_TYPE_ALL = 0xFF

# Link modes (protocol types)
LINK_MODE_TCP = 0
LINK_MODE_UDP = 1
LINK_MODE_MULTICAST = 2
LINK_MODE_RTP = 3
LINK_MODE_RTP_RTSP = 4
LINK_MODE_RTSP_HTTP = 5

# File types for search
FILE_TYPE_ALL = 0xFF
FILE_TYPE_TIMING = 0        # Scheduled record
FILE_TYPE_MOTION = 1        # Motion detection
FILE_TYPE_ALARM = 2         # Alarm record
FILE_TYPE_MOTION_OR_ALARM = 3
FILE_TYPE_MOTION_AND_ALARM = 4
FILE_TYPE_COMMAND = 5       # Command trigger
FILE_TYPE_MANUAL = 6        # Manual record
FILE_TYPE_VCA = 7           # VCA record

# Lock status for file search
LOCK_STATUS_ALL = 0xFF
LOCK_STATUS_UNLOCKED = 0
LOCK_STATUS_LOCKED = 1

# Login modes
LOGIN_MODE_PRIVATE = 0
LOGIN_MODE_ISAPI = 1
LOGIN_MODE_ADAPT = 2

# Real data callback types
NET_DVR_SYSHEAD = 1         # System header
NET_DVR_STREAMDATA = 2      # Stream data (video/audio mixed)
NET_DVR_AUDIOSTREAMDATA = 3 # Audio stream data
NET_DVR_STD_VIDEODATA = 4   # Standard video data
NET_DVR_STD_AUDIODATA = 5   # Standard audio data

# Preview modes
PREVIEW_MODE_NORMAL = 0
PREVIEW_MODE_DELAY = 2

# PTZ Commands
PTZ_UP = 21
PTZ_DOWN = 22
PTZ_LEFT = 23
PTZ_RIGHT = 24
PTZ_UP_LEFT = 25
PTZ_UP_RIGHT = 26
PTZ_DOWN_LEFT = 27
PTZ_DOWN_RIGHT = 28
PTZ_ZOOM_IN = 11
PTZ_ZOOM_OUT = 12
PTZ_FOCUS_NEAR = 13
PTZ_FOCUS_FAR = 14
PTZ_IRIS_OPEN = 15
PTZ_IRIS_CLOSE = 16
PTZ_AUTO_PAN = 29
PTZ_LIGHT_ON = 2
PTZ_LIGHT_OFF = 3
PTZ_WIPER_ON = 4
PTZ_WIPER_OFF = 5

# PTZ Preset Commands
PTZ_PRESET_SET = 8
PTZ_PRESET_CLEAR = 9
PTZ_PRESET_GOTO = 39

# PTZ Cruise Commands
PTZ_CRUISE_RUN = 37
PTZ_CRUISE_STOP = 38
PTZ_CRUISE_FILL_PRESET = 30
PTZ_CRUISE_SET_SPEED = 34
PTZ_CRUISE_SET_DWELL = 35
PTZ_CRUISE_CLEAR = 36

# PTZ Track (Pattern) Commands
PTZ_TRACK_START_RECORD = 31
PTZ_TRACK_STOP_RECORD = 32
PTZ_TRACK_RUN = 33

# Alarm message types
COMM_ALARM = 0x1100              # Alarm upload
COMM_ALARM_V30 = 0x4000          # Alarm V30
COMM_ALARM_V40 = 0x4007          # Alarm V40
COMM_ALARM_RULE = 0x1102         # Behavior analysis alarm
COMM_ALARM_PDC = 0x1103          # People counting alarm
COMM_UPLOAD_FACESNAP_RESULT = 0x1112  # Face capture result
COMM_SNAP_MATCH_ALARM = 0x2902   # Face match alarm
COMM_VCA_ALARM = 0x4993          # VCA alarm

# Alarm types
ALARM_TYPE_MOTION = 3            # Motion detection
ALARM_TYPE_VIDEO_LOSS = 2        # Video loss
ALARM_TYPE_VIDEO_TAMPER = 5      # Video tampering
ALARM_TYPE_IO_ALARM = 1          # IO alarm
ALARM_TYPE_VCA = 0               # VCA event

# Error codes (common ones)
NET_DVR_NOERROR = 0
NET_DVR_PASSWORD_ERROR = 1
NET_DVR_NOENOUGHPRI = 2
NET_DVR_NOINIT = 3
NET_DVR_CHANNEL_ERROR = 4
NET_DVR_OVER_MAXLINK = 5
NET_DVR_VERSIONNOMATCH = 6
NET_DVR_NETWORK_FAIL_CONNECT = 7
NET_DVR_NETWORK_SEND_ERROR = 8
NET_DVR_NETWORK_RECV_ERROR = 9
NET_DVR_NETWORK_RECV_TIMEOUT = 10
NET_DVR_NETWORK_ERRORDATA = 11
NET_DVR_ORDER_ERROR = 12
NET_DVR_OPERNOPERMIT = 13
NET_DVR_COMMANDTIMEOUT = 14
NET_DVR_ERRORSERIALPORT = 15
NET_DVR_ERRORALARMPORT = 16
NET_DVR_PARAMETER_ERROR = 17
NET_DVR_CHAN_EXCEPTION = 18
NET_DVR_NODISK = 19
NET_DVR_ERRORDISKNUM = 20
NET_DVR_DISK_FULL = 21
NET_DVR_DISK_ERROR = 22
NET_DVR_NOSUPPORT = 23
NET_DVR_BUSY = 24
NET_DVR_MODIFY_FAIL = 25
NET_DVR_PASSWORD_FORMAT_ERROR = 26
NET_DVR_DISK_FORMATING = 27
NET_DVR_DVRNORESOURCE = 28
NET_DVR_DVROPRATEFAILED = 29
NET_DVR_OPENHOSTSOUND_FAIL = 30
NET_DVR_DABORDEVOPERATE_FAIL = 31
NET_DVR_AUDIO_MODE_ERROR = 32
NET_DVR_NOOPENPREVIEW = 33
NET_DVR_CREATESOCKET_ERROR = 34
NET_DVR_SETSOCKET_ERROR = 35
NET_DVR_MAX_NUM = 36
NET_DVR_USERNOTEXIST = 37
NET_DVR_WRITEFLASHERROR = 38
NET_DVR_UPGRADEFAIL = 39
NET_DVR_CARABORDEVOPEN_FAIL = 40
NET_DVR_LOCESSION_FAIL = 41
NET_DVR_NOENCODEING = 42
NET_DVR_IABORDEVOPEN_FAIL = 43
NET_DVR_DEV_OFFLINE = 44
NET_DVR_USER_LOCKED = 47
NET_DVR_BINDSOCKET_ERROR = 72
NET_DVR_SOCKETCLOSE_ERROR = 73
NET_DVR_USERID_ISUSING = 74
NET_DVR_USEREXIST = 75

# Error code to message mapping
ERROR_MESSAGES = {
    NET_DVR_NOERROR: "No error",
    NET_DVR_PASSWORD_ERROR: "Username or password error",
    NET_DVR_NOENOUGHPRI: "Not enough privilege",
    NET_DVR_NOINIT: "SDK not initialized",
    NET_DVR_CHANNEL_ERROR: "Channel error",
    NET_DVR_OVER_MAXLINK: "Over maximum connections",
    NET_DVR_VERSIONNOMATCH: "Version mismatch",
    NET_DVR_NETWORK_FAIL_CONNECT: "Network connection failed",
    NET_DVR_NETWORK_SEND_ERROR: "Network send error",
    NET_DVR_NETWORK_RECV_ERROR: "Network receive error",
    NET_DVR_NETWORK_RECV_TIMEOUT: "Network receive timeout",
    NET_DVR_NETWORK_ERRORDATA: "Network error data",
    NET_DVR_ORDER_ERROR: "Order error",
    NET_DVR_OPERNOPERMIT: "Operation not permitted",
    NET_DVR_COMMANDTIMEOUT: "Command timeout",
    NET_DVR_PARAMETER_ERROR: "Parameter error",
    NET_DVR_NOSUPPORT: "Not supported",
    NET_DVR_BUSY: "Device busy",
    NET_DVR_DEV_OFFLINE: "Device offline",
    NET_DVR_USER_LOCKED: "User locked",
}


def get_error_message(error_code: int) -> str:
    """Get human-readable error message for error code."""
    return ERROR_MESSAGES.get(error_code, f"Unknown error ({error_code})")
